version: 2.1

workflows:
  version: 2
  build_pipeline:
    jobs:
      - build
      - integrated_test:
          requires:
            - build
      - deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
commands:
  bootstrap:
    steps:
      - restore_cache:
          name: Restore npm packages
          keys:
            - dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: Bootstrap workspaces
          command: |
            yarn install --frozen-lockfile
            yarn bootstrap
      - save_cache:
          name: Store npm packages
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

jobs:
  build:
    docker:
      - image: node:17
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run: yarn format:check
      - run: yarn build
      - run: yarn lint
      - run: yarn test

  integrated_test:
    docker:
      - image: regviz/node-xcb
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    parallelism: 4
    steps:
      - checkout
      - bootstrap
      - run: yarn build
      - run: yarn e2e
  #     - run: yarn regression

  deploy:
    docker:
      - image: node:17
    working_directory: ~/repo
    steps:
      - checkout
      - bootstrap
      - run:
          name: Login npm
          command: |
            echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > ~/.npmrc
            npm whoami
      - run:
          name: Publish
          command: |
            yarn deploy:ci
